[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
httpcore = "<=0.15"
importlib-metadata="^4.13.0"
uvicorn = "^0.20.0"
fastapi = "^0.80.0"
python-multipart = "^0.0.5"
email-validator = "^1.0.5"
requests = "^2.23.0"
celery = "^4.4.7"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
tenacity = "^6.1.0"
pydantic = "^1.9.0"
emails = "^0.5.15"
raven = "^6.10.0"
gunicorn = "^20.0.4"
jinja2 = "^3.1.2"
psycopg2-binary = "^2.9.5"
alembic = "^1.9.0"
sqlalchemy = "^1.3.16"
pytest = "^7.2.0"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}

[tool.poetry.dev-dependencies]
mypy = "^0.991"
black = "^19.10b0"
isort = "^5.11.4"
autoflake = "^1.7.8"
flake8 = "^3.7.9"
pytest = "^7.2.0"
sqlalchemy-stubs = "^0.3"
pytest-cov = "^4.0.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

