default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  domain_main: '{{ cookiecutter.domain_main }}'
  domain_staging: '{{ cookiecutter.domain_staging }}'
  domain_base_api_url: '{{cookiecutter.domain_base_api_url}}'
  domain_base_ws_url: '{{cookiecutter.domain_base_ws_url}}'
  docker_swarm_stack_name_main: '{{ cookiecutter.docker_swarm_stack_name_main }}'
  docker_swarm_stack_name_staging: '{{ cookiecutter.docker_swarm_stack_name_staging }}'
  secret_key: '{{ cookiecutter.secret_key }}'
  first_superuser: '{{ cookiecutter.first_superuser }}'
  first_superuser_password: '{{ cookiecutter.first_superuser_password }}'
  backend_cors_origins: '{{ cookiecutter.backend_cors_origins }}'
  smtp_port: '{{ cookiecutter.smtp_port }}'
  smtp_host: '{{ cookiecutter.smtp_host }}'
  smtp_user: '{{ cookiecutter.smtp_user }}'
  smtp_password: '{{ cookiecutter.smtp_password }}'
  smtp_emails_from_email: '{{ cookiecutter.smtp_emails_from_email }}'
  smtp_emails_from_name: '{{cookiecutter.smtp_emails_from_name}}'
  smtp_emails_to_email: '{{cookiecutter.smtp_emails_to_email}}'
  postgres_password: '{{ cookiecutter.postgres_password }}'
  pgadmin_default_user: '{{ cookiecutter.pgadmin_default_user }}'
  pgadmin_default_user_password: '{{ cookiecutter.pgadmin_default_user_password }}'
  neo4j_password: '{{cookiecutter.neo4j_password}}'
  traefik_constraint_tag: '{{ cookiecutter.traefik_constraint_tag }}'
  traefik_constraint_tag_staging: '{{ cookiecutter.traefik_constraint_tag_staging }}'
  traefik_public_constraint_tag: '{{ cookiecutter.traefik_public_constraint_tag }}'
  flower_auth: '{{ cookiecutter.flower_auth }}'
  sentry_dsn: '{{ cookiecutter.sentry_dsn }}'
  docker_image_prefix: '{{ cookiecutter.docker_image_prefix }}'
  docker_image_backend: '{{ cookiecutter.docker_image_backend }}'
  docker_image_celeryworker: '{{ cookiecutter.docker_image_celeryworker }}'
  docker_image_frontend: '{{ cookiecutter.docker_image_frontend }}'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
