default_context:
  project_name: 'ptar'
  project_slug: 'ptar'
  domain_main: 'ptar.com'
  domain_staging: 'stag.ptar.com'
  docker_swarm_stack_name_main: 'ptar-com'
  docker_swarm_stack_name_staging: 'stag-ptar-com'
  secret_key: 'eternity'
  first_superuser: 'admin@ptar.com'
  first_superuser_password: 'eternity'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ptar.com", "https://stag.ptar.com", "https://ptar.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@ptar.com'
  postgres_password: 'eternity'
  pgadmin_default_user: 'admin@ptar.com'
  pgadmin_default_user_password: 'eternity'
  traefik_constraint_tag: 'ptar.com'
  traefik_constraint_tag_staging: 'stag.ptar.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:eternity'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
